name: Release

on:
  push:
    branches:
      - master
      - main
      - beta

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Node.JS
        uses: actions/setup-node@v1
        with:
            node-version: "14.17"
      - name: Release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npx semantic-release